name: Deploy to ECS (Fargate)

on:
  push:
    branches: ["aws-docker"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPO: coverletter-generator
  ECS_CLUSTER: coverletter-cluster
  ECS_SERVICE: coverletter-task-service-kt2tz1qs
  TASK_FAMILY: coverletter-task
  CONTAINER_NAME: coverletter

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${GITHUB_SHA}"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

          docker buildx create --use || true
          docker buildx build \
            --platform linux/amd64 \
            -t "$IMAGE_URI" \
            --push \
            .

      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition "${TASK_FAMILY}" \
            --query taskDefinition > taskdef.json

      - name: Register new task definition revision
        run: |
          cat taskdef.json \
          | jq 'del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            )
            | (.containerDefinitions[] | select(.name=="'${CONTAINER_NAME}'") | .image) = env.IMAGE_URI
          ' > taskdef-new.json

          NEW_TD_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://taskdef-new.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          echo "NEW_TD_ARN=$NEW_TD_ARN" >> $GITHUB_ENV

      - name: Deploy to ECS service
        run: |
          aws ecs update-service \
            --cluster "${ECS_CLUSTER}" \
            --service "${ECS_SERVICE}" \
            --task-definition "${NEW_TD_ARN}"

          aws ecs wait services-stable \
            --cluster "${ECS_CLUSTER}" \
            --services "${ECS_SERVICE}"
